#!/bin/bash

# Utility function to create virtual environments

venv_dir=$OPENSHIFT_PYTHON_DIR/virtenv/venv

function relative-virtenv {
  pushd "$venv_dir" > /dev/null

  vdir=$(cd "${venv_dir}" && pwd)
  for zf in $(grep -l -r "#\!$vdir/venv/bin/" . ); do
    sed --follow-symlinks -i "s;#\!$vdir/venv/bin/;#\!/usr/bin/env ;" "$zf"
  done

  popd > /dev/null
}

function create-virtenv {
  if [ ! -d "$venv_dir" ]  ||  ! $(ls "$venv_dir" > /dev/null 2>&1); then
    python3 -m venv --system-site-packages --clear --without-pip $venv_dir
  fi

  if ! $(ls $venv_dir/bin/pip > /dev/null 2>&1); then
    install_pip
  fi

  relative-virtenv
}

function install_pip() {
  pushd "$venv_dir/bin" > /dev/null
  \cp $OPENSHIFT_PYTHON_DIR/conda/bin/pip .
  \sed -r -i "1s;.*;#!$PWD/python;" pip
  popd > /dev/null
}

function activate-virtenv {
  source $venv_dir/bin/activate
}
